services:
  backend:
    image: clicker-backend:latest
    container_name: clicker-backend
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    image: clicker-frontend:latest
    container_name: clicker-frontend
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

# docker-compose up -d --build
# docker-compose down
