name: CI/CD Pipeline

# Exécution sur push et pull request vers main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- JOB 1 : TESTS UNITAIRES (Intégration Continue) ---
  test-backend:
    name: "Run Backend Tests"
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des dépendances
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Lancement des Tests (Pytest)
        working-directory: ./backend
        env:
          REDIS_HOST: localhost 
        run: pytest

  # --- JOB 2 : BUILD DOCKER (Livraison Continue) ---
  build-images:
    name: "Build Docker Images"
    needs: test-backend
    runs-on: ubuntu-latest
    env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: env.DOCKER_USERNAME != ''
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: m0ii0m69/clicker-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: m0ii0m69/clicker-frontend:latest

  # --- JOB 3 : DÉPLOIEMENT (Production) ---
  deploy:
    name: "Deploy to Production"
    needs: build-images
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: docker-compose up -d --build --remove-orphans

      - name: Cleanup unused images
        run: docker image prune -f
