name: CI/CD Pipeline

# Déclenchement sur push et pull request vers main (Comme dans le TD)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1 : TESTS UNITAIRES (Intégration Continue) ---
  test-backend:
    name: "Run Backend Tests"
    runs-on: ubuntu-latest
    
    # On lance un service Redis temporaire pour que les tests fonctionnent
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Récupération du code (Checkout)
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des dépendances
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Lancement des Tests (Pytest)
        working-directory: ./backend
        env:
          REDIS_HOST: localhost 
        run: pytest

  # --- JOB 2 : BUILD DOCKER (Livraison Continue) ---
  build-images:
    name: "Build Docker Images"
    # Condition critique du projet : "Si Test = OK alors Image docker"
    needs: test-backend
    runs-on: ubuntu-latest
    env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        # Ne s'execute que si les secrets sont configurés (éviter échec en fork)
        if: env.DOCKER_USERNAME != ''
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: m0ii0m69/paperclip-backend:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: m0ii0m69/paperclip-frontend:latest


  # --- JOB 3 : DÉPLOIEMENT CONTINU (CD) ---
  deploy:
    name: "Deploy to Kubernetes"
    needs: build-images
    runs-on: ubuntu-latest
    
    steps:
      - name: Simulation de déploiement
        run: |
          echo "Simulating deployment to Kubernetes..."
          echo "Applying manifests from ./k8s/"
          echo "kubectl apply -f ./k8s/"
          
      - name: Checkout Code (pour récupérer les manifestes)
        uses: actions/checkout@v3
